package GUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.table.DefaultTableModel;
import java.util.Vector;
import BUS.*;
import DTO.*;

/**
 *
 * @author HuyHoang
 */
public class bill_detail_GUI extends javax.swing.JFrame {

    /**
     * Creates new form bill_detail_GUI
     */
    public bill_detail_GUI(int bill_id, int staff_id, int customer_id) {
        initComponents();
        loadData(bill_id, staff_id, customer_id);
    }

    private void initHeader() {
        this.picture_header = new Vector();
        this.picture_header.add("ID");
        this.picture_header.add("Barcode");
        this.picture_header.add("Type");
        this.picture_header.add("Price");
        this.picture_header.add("Promotion");
        this.picture_header.add("Description");
    }

    private void loadData(int bill_id, int staff_id, int customer_id) {
        Bill bill = bill_BUS.getBillByID(bill_id);

        if (bill != null) {
            loadDataPicture(bill_id);
            loadDataStaff(staff_id);
            loadDataCustomer(customer_id);

            bill_no_label.setText(String.valueOf(bill.getID()));
            label_total_value.setText(String.valueOf(bill.getTotal()));
            label_date_value.setText(bill.getDateString());
            setTitle("Bill NO - " + bill.getID());
        }
    }

    private void loadDataStaff(int staff_id) {
        staff = staff_BUS.getStaffByID(String.valueOf(staff_id));

        updateStaffInfoUI();
    }

    private void updateStaffInfoUI() {
        if (staff != null) {
            jTextField_staff_name.setText(staff.getName());
            jTextField_staff_phone.setText(staff.getPhone());
            jTextField_staff_gender.setText(staff.getSex());
            jTextField_staff_start_date.setText(staff.getDateStartString());
            jTextField_staff_end_date.setText(staff.getDateEndString());
        }
    }

    private void loadDataCustomer(int customer_id) {
        customer = customer_BUS.getCustomerByID(customer_id);

        updateCustomerInfoUI();
    }

    private void updateCustomerInfoUI() {
        if (customer != null) {
            jTextField_cus_name.setText(customer.getName());
            jTextField_cus_type.setText(String.valueOf(customer.getType()));
            jTextField_cus_phone.setText(customer.getPhone());
        }
    }

    private void loadDataPicture(int bill_id) {
        picture_data.clear();
        picture_data.addAll(picture_BUS.getPicturesByBillID(bill_id));

        picture_tableModel.fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        jPanel_parent_container = new javax.swing.JPanel();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        jPanel_label = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        bill_no_label = new java.awt.Label();
        jPanel_picture_table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_picture = new javax.swing.JTable();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        jPanel_bill_info = new javax.swing.JPanel();
        jPanel_bill_date = new javax.swing.JPanel();
        label_date_label = new java.awt.Label();
        label_date_value = new java.awt.Label();
        jPanel_bill_total = new javax.swing.JPanel();
        label_total_label = new java.awt.Label();
        label_total_value = new java.awt.Label();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        jPanel_info = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        jPanel_info_inner = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        jPanel_staff_parent = new javax.swing.JPanel();
        label_staff_info = new java.awt.Label();
        jPanel_staff = new javax.swing.JPanel();
        jLabel_staff_name = new javax.swing.JLabel();
        jTextField_staff_name = new javax.swing.JTextField();
        jLabel_staff_phone = new javax.swing.JLabel();
        jTextField_staff_phone = new javax.swing.JTextField();
        jLabel_staff_gender = new javax.swing.JLabel();
        jTextField_staff_gender = new javax.swing.JTextField();
        jLabel_staff_start_date = new javax.swing.JLabel();
        jTextField_staff_start_date = new javax.swing.JTextField();
        jLabel_staff_end_date = new javax.swing.JLabel();
        jTextField_staff_end_date = new javax.swing.JTextField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        jPanel_cus_parent = new javax.swing.JPanel();
        label_customer_info = new java.awt.Label();
        jPanel_customer = new javax.swing.JPanel();
        jLabel_cus_name = new javax.swing.JLabel();
        jTextField_cus_name = new javax.swing.JTextField();
        jLabel_cus_type = new javax.swing.JLabel();
        jTextField_cus_type = new javax.swing.JTextField();
        jLabel_cus_phone = new javax.swing.JLabel();
        jTextField_cus_phone = new javax.swing.JTextField();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 15), new java.awt.Dimension(0, 15), new java.awt.Dimension(32767, 15));
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(filler6);

        jPanel_parent_container.setLayout(new javax.swing.BoxLayout(jPanel_parent_container, javax.swing.BoxLayout.Y_AXIS));
        jPanel_parent_container.add(filler8);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label1.setText("Bill No:");
        jPanel_label.add(label1);

        bill_no_label.setAlignment(java.awt.Label.CENTER);
        bill_no_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel_label.add(bill_no_label);

        jPanel_parent_container.add(jPanel_label);

        jPanel_picture_table.setLayout(new javax.swing.BoxLayout(jPanel_picture_table, javax.swing.BoxLayout.Y_AXIS));

        picture_data = new Vector<>();
        initHeader();

        picture_tableModel = new DefaultTableModel(
                picture_data, picture_header
        ) {
            Class[] types = new Class [] {
                    String.class, String.class, Integer.class, Integer.class, String.class, String.class
            };
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };

        jTable_picture.setModel(picture_tableModel);

        jScrollPane2.setViewportView(jTable_picture);

        jScrollPane1.setViewportView(jScrollPane2);

        jPanel_picture_table.add(jScrollPane1);
        jPanel_picture_table.add(filler11);

        jPanel_bill_info.setLayout(new java.awt.GridLayout(1, 2));

        jPanel_bill_date.setLayout(new javax.swing.BoxLayout(jPanel_bill_date, javax.swing.BoxLayout.LINE_AXIS));

        label_date_label.setAlignment(java.awt.Label.RIGHT);
        label_date_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_date_label.setText("Date:");
        jPanel_bill_date.add(label_date_label);

        label_date_value.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel_bill_date.add(label_date_value);

        jPanel_bill_info.add(jPanel_bill_date);

        jPanel_bill_total.setLayout(new javax.swing.BoxLayout(jPanel_bill_total, javax.swing.BoxLayout.LINE_AXIS));

        label_total_label.setAlignment(java.awt.Label.RIGHT);
        label_total_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_total_label.setText("Total:");
        jPanel_bill_total.add(label_total_label);

        label_total_value.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel_bill_total.add(label_total_value);
        label_total_value.getAccessibleContext().setAccessibleName("");

        jPanel_bill_info.add(jPanel_bill_total);

        jPanel_picture_table.add(jPanel_bill_info);
        jPanel_picture_table.add(filler10);

        jPanel_parent_container.add(jPanel_picture_table);

        jPanel_info.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_info.setLayout(new javax.swing.BoxLayout(jPanel_info, javax.swing.BoxLayout.Y_AXIS));
        jPanel_info.add(filler4);

        jPanel_info_inner.setLayout(new javax.swing.BoxLayout(jPanel_info_inner, javax.swing.BoxLayout.LINE_AXIS));
        jPanel_info_inner.add(filler1);

        jPanel_staff_parent.setLayout(new javax.swing.BoxLayout(jPanel_staff_parent, javax.swing.BoxLayout.Y_AXIS));

        label_staff_info.setAlignment(java.awt.Label.CENTER);
        label_staff_info.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        label_staff_info.setText("Staff Infomation");
        jPanel_staff_parent.add(label_staff_info);

        jPanel_staff.setLayout(new java.awt.GridLayout(5, 2, 0, 10));

        jLabel_staff_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_staff_name.setText("Name");
        jPanel_staff.add(jLabel_staff_name);

        jTextField_staff_name.setEditable(false);
        jTextField_staff_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_staff_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_staff_nameActionPerformed(evt);
            }
        });
        jPanel_staff.add(jTextField_staff_name);

        jLabel_staff_phone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_staff_phone.setText("Phone");
        jPanel_staff.add(jLabel_staff_phone);

        jTextField_staff_phone.setEditable(false);
        jTextField_staff_phone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel_staff.add(jTextField_staff_phone);

        jLabel_staff_gender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_staff_gender.setText("Gender");
        jPanel_staff.add(jLabel_staff_gender);

        jTextField_staff_gender.setEditable(false);
        jTextField_staff_gender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel_staff.add(jTextField_staff_gender);

        jLabel_staff_start_date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_staff_start_date.setText("Start date");
        jPanel_staff.add(jLabel_staff_start_date);

        jTextField_staff_start_date.setEditable(false);
        jTextField_staff_start_date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel_staff.add(jTextField_staff_start_date);

        jLabel_staff_end_date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_staff_end_date.setText("End date");
        jPanel_staff.add(jLabel_staff_end_date);

        jTextField_staff_end_date.setEditable(false);
        jTextField_staff_end_date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel_staff.add(jTextField_staff_end_date);

        jPanel_staff_parent.add(jPanel_staff);

        jPanel_info_inner.add(jPanel_staff_parent);
        jPanel_info_inner.add(filler3);

        jPanel_cus_parent.setLayout(new javax.swing.BoxLayout(jPanel_cus_parent, javax.swing.BoxLayout.Y_AXIS));

        label_customer_info.setAlignment(java.awt.Label.CENTER);
        label_customer_info.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        label_customer_info.setText("Customer Infomation");
        jPanel_cus_parent.add(label_customer_info);

        jPanel_customer.setLayout(new java.awt.GridLayout(3, 2, 0, 10));

        jLabel_cus_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_cus_name.setText("Name");
        jPanel_customer.add(jLabel_cus_name);

        jTextField_cus_name.setEditable(false);
        jTextField_cus_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel_customer.add(jTextField_cus_name);

        jLabel_cus_type.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_cus_type.setText("Type");
        jPanel_customer.add(jLabel_cus_type);

        jTextField_cus_type.setEditable(false);
        jTextField_cus_type.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel_customer.add(jTextField_cus_type);

        jLabel_cus_phone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_cus_phone.setText("Phone");
        jPanel_customer.add(jLabel_cus_phone);

        jTextField_cus_phone.setEditable(false);
        jTextField_cus_phone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel_customer.add(jTextField_cus_phone);

        jPanel_cus_parent.add(jPanel_customer);

        jPanel_info_inner.add(jPanel_cus_parent);
        jPanel_info_inner.add(filler2);

        jPanel_info.add(jPanel_info_inner);
        jPanel_info.add(filler5);

        jPanel_parent_container.add(jPanel_info);
        jPanel_parent_container.add(filler9);

        getContentPane().add(jPanel_parent_container);
        getContentPane().add(filler7);

        pack();
    }// </editor-fold>

    private void jTextField_staff_nameActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    // Bill info data
    Customer customer;
    Staff staff;

    // Table data
    Vector picture_header;
    Vector<Vector> picture_data;
    DefaultTableModel picture_tableModel;

    // Variables declaration - do not modify
    private java.awt.Label bill_no_label;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JLabel jLabel_cus_name;
    private javax.swing.JLabel jLabel_cus_phone;
    private javax.swing.JLabel jLabel_cus_type;
    private javax.swing.JLabel jLabel_staff_end_date;
    private javax.swing.JLabel jLabel_staff_gender;
    private javax.swing.JLabel jLabel_staff_name;
    private javax.swing.JLabel jLabel_staff_phone;
    private javax.swing.JLabel jLabel_staff_start_date;
    private javax.swing.JPanel jPanel_bill_date;
    private javax.swing.JPanel jPanel_bill_info;
    private javax.swing.JPanel jPanel_bill_total;
    private javax.swing.JPanel jPanel_cus_parent;
    private javax.swing.JPanel jPanel_customer;
    private javax.swing.JPanel jPanel_info;
    private javax.swing.JPanel jPanel_info_inner;
    private javax.swing.JPanel jPanel_label;
    private javax.swing.JPanel jPanel_parent_container;
    private javax.swing.JPanel jPanel_picture_table;
    private javax.swing.JPanel jPanel_staff;
    private javax.swing.JPanel jPanel_staff_parent;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_picture;
    private javax.swing.JTextField jTextField_cus_name;
    private javax.swing.JTextField jTextField_cus_phone;
    private javax.swing.JTextField jTextField_cus_type;
    private javax.swing.JTextField jTextField_staff_end_date;
    private javax.swing.JTextField jTextField_staff_gender;
    private javax.swing.JTextField jTextField_staff_name;
    private javax.swing.JTextField jTextField_staff_phone;
    private javax.swing.JTextField jTextField_staff_start_date;
    private java.awt.Label label1;
    private java.awt.Label label_customer_info;
    private java.awt.Label label_date_label;
    private java.awt.Label label_date_value;
    private java.awt.Label label_staff_info;
    private java.awt.Label label_total_label;
    private java.awt.Label label_total_value;
    // End of variables declaration
}

