package GUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Vector;
import BUS.*;
import DTO.Bill;

/**
 *
 * @author HuyHoang
 */
public class bill_GUI extends javax.swing.JFrame {

    /**
     * Creates new form bill_GUI
     */
    public bill_GUI() {
        initComponents();
        setItemInTableClickListener();
        loadData();
    }

    private void setItemInTableClickListener() {
        jTable_bill.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent me) {
                if (me.getClickCount() == 2) {     // to detect doble click events
                    JTable target = (JTable)me.getSource();
                    int row = target.getSelectedRow(); // select a row
                    int column = target.getSelectedColumn(); // select a column
                    Vector row_data = bill_tableModel.getDataVector().elementAt(row);

                    int bill_id = (int)row_data.get(0);
                    perform_show_bill_detail(bill_id);
                }
            }
        });
    }

    private void perform_show_bill_detail(int bill_id) {
        Bill bill = bill_BUS.getBillByID(bill_id);

        if (bill != null) {
            int staff_id = bill.getStaff_ID();
            int customer_id = bill.getCustomer_ID();

            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new bill_detail_GUI(bill_id, staff_id, customer_id).setVisible(true);
                }
            });
        }
    }

    private void loadData() {
        bill_data.clear();
        bill_data.addAll(bill_BUS.getAllBills());

        bill_tableModel.fireTableDataChanged();
    }

    private void initHeader() {
        this.bill_header = new Vector();
        this.bill_header.add("ID");
        this.bill_header.add("Total");
        this.bill_header.add("Staff ID");
        this.bill_header.add("Customer ID");
        this.bill_header.add("Date");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        label1 = new java.awt.Label();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jPanel1 = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_bill = new javax.swing.JTable();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));
        getContentPane().add(filler1);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label1.setText("Bill Management");
        getContentPane().add(label1);
        getContentPane().add(filler3);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(filler4);

        initHeader();

        bill_data = new Vector<>();
        bill_tableModel = new DefaultTableModel(
                bill_data, bill_header
        ) {
            Class[] types = new Class [] {
                    Integer.class, Integer.class, Integer.class, Integer.class, String.class
            };
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };

        jTable_bill.setModel(bill_tableModel);

        jScrollPane2.setViewportView(jTable_bill);

        jScrollPane1.setViewportView(jScrollPane2);

        jPanel1.add(jScrollPane1);
        jPanel1.add(filler5);

        getContentPane().add(jPanel1);
        getContentPane().add(filler2);

        pack();
    }// </editor-fold>

    // table data
    Vector bill_header;
    Vector<Vector> bill_data;
    DefaultTableModel bill_tableModel;

    // Variables declaration - do not modify
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_bill;
    private java.awt.Label label1;
    // End of variables declaration
}

