/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import BUS.staff_BUS;
import DTO.Staff;

import java.util.Vector;
import javax.swing.table.*;

/**
 *
 * @author duyph
 */
public class staff_GUI extends javax.swing.JFrame {

    /**
     * Creates new form staff_GUI
     */
    public staff_GUI() {
        initComponents();
        initHeader();
        loadData();
    }
    
    private void initHeader(){
        this.table_header = new Vector();
        this.table_header.add("ID");
        this.table_header.add("Name");
        this.table_header.add("Phone");
        this.table_header.add("Sex");
        this.table_header.add("Date start");
        this.table_header.add("Date end");
        this.table_header.add("Status");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTable1 = new javax.swing.JTable();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        frameLabel = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        phone = new javax.swing.JTextField();
        dateStart = new javax.swing.JTextField();
        dateEnd = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        sex = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        name_lb = new javax.swing.JLabel();
        sex_lb = new javax.swing.JLabel();
        status_lb = new javax.swing.JLabel();
        phone_lb = new javax.swing.JLabel();
        dateStart_lb = new javax.swing.JLabel();
        dateEnd_lb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        frameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        frameLabel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        frameLabel.setText("Staff Management");
        frameLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        phone.setMinimumSize(new java.awt.Dimension(100, 20));

        dateStart.setMinimumSize(new java.awt.Dimension(100, 20));

        dateEnd.setMinimumSize(new java.awt.Dimension(100, 20));

        name.setMinimumSize(new java.awt.Dimension(100, 20));

        sex.setMinimumSize(new java.awt.Dimension(100, 20));

        status.setMinimumSize(new java.awt.Dimension(100, 20));

        name_lb.setText("Name");

        sex_lb.setText("Sex");

        status_lb.setText("Status");

        phone_lb.setText("Phone");

        dateStart_lb.setText("Date start");

        dateEnd_lb.setText("Date end");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(name_lb)
                    .addComponent(sex_lb)
                    .addComponent(status_lb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(sex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateStart_lb, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(phone_lb, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateEnd_lb, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(phone, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(dateStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(157, 157, 157))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_lb)
                    .addComponent(phone_lb))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sex_lb)
                    .addComponent(dateStart_lb))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status_lb)
                    .addComponent(dateEnd_lb))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(frameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadData(){
        this.data = staff_BUS.getAllStaff();
        
        jTable3.setModel(new DefaultTableModel(data, this.table_header){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
    }

//    private Staff toStaff(Vector vector){
//        String ID = (String) vector.get(0);
//        String name = (String) vector.get(1);
//        String phone = (String) vector.get(2);
//        String sex = (String) vector.get(3);
//        String dateStart = (String) vector.get(4);
//        String dateEnd  = (String) vector.get(5);
//        int status = (Integer) vector.get(6);
//
//        return st
//    }


    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        int selectedRowIndex = jTable3.getSelectedRow();
        Vector vector = this.data.get(selectedRowIndex);

        String ID = (String) vector.get(0);
        String name = (String) vector.get(1);
        String phone = (String) vector.get(2);
        String sex = (String) vector.get(3);
        String dateStart = (String) vector.get(4);
        String dateEnd  = (String) vector.get(5);
        int status = (Integer) vector.get(6);

        this.name.setText(name);
        this.phone.setText(phone);
        this.sex.setText(sex);
        this.dateStart.setText(dateStart);
        this.dateEnd.setText(dateEnd);
        this.status.setText(String.valueOf(status));


        
    }//GEN-LAST:event_jTable3MouseClicked

    
    private Vector table_header;
    private Vector<Vector> data;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel status_lb;
    private javax.swing.JLabel phone_lb;
    private javax.swing.JLabel dateStart_lb;
    private javax.swing.JLabel dateEnd_lb;
    private javax.swing.JLabel name_lb;
    private javax.swing.JLabel sex_lb;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField dateEnd;
    private javax.swing.JTextField name;
    private javax.swing.JTextField sex;
    private javax.swing.JTextField status;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField dateStart;
    private javax.swing.JTextField frameLabel;
    // End of variables declaration//GEN-END:variables
}
