package GUI;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HuyHoang
 */
public class start_menu_GUI extends javax.swing.JFrame {

    /**
     * Creates new form start_menu_GUI
     */
    public start_menu_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jPanel_main = new javax.swing.JPanel();
        jPanel_list_picture = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jScrollPane_list_picture = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel_input = new javax.swing.JPanel();
        jPanel_customer = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        jPanel_cutomer_inner = new javax.swing.JPanel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        textField_cus_name = new java.awt.TextField();
        jLabel3 = new javax.swing.JLabel();
        textField_cus_addr = new java.awt.TextField();
        jLabel4 = new javax.swing.JLabel();
        textField_cus_phone = new java.awt.TextField();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));
        jPanel_picture = new javax.swing.JPanel();
        label6 = new java.awt.Label();
        jPanel_picture_inner = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textField_pic_barcode = new java.awt.TextField();
        jLabel5 = new javax.swing.JLabel();
        textField_pic_name = new java.awt.TextField();
        jLabel6 = new javax.swing.JLabel();
        textField_pic_price = new java.awt.TextField();
        jButton_find_picture = new javax.swing.JButton();
        jButton_add_to_bill = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jPanel_bill = new javax.swing.JPanel();
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        jPanel_bill_inner = new javax.swing.JPanel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jPanel_bill_info = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_bill_no = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_bill_customer_name = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField_bill_customer_addr = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField_bill_customer_phone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField_bill_customer_date = new javax.swing.JTextField();
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jScrollPane_bill = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel_bill_end_panel = new javax.swing.JPanel();
        jButton_bill_pay = new javax.swing.JButton();
        jButton_bill_print = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextField_bill_total = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField_bill_staff = new javax.swing.JTextField();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        jPanel_navigator = new javax.swing.JPanel();
        jButton_manage_picture = new javax.swing.JButton();
        jButton_manage_promotion = new javax.swing.JButton();
        jButton_manage_staff = new javax.swing.JButton();
        jButton_manage_customer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("art gallery store");

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label1.setText("Art gallery store");
        jPanel1.add(label1);

        jPanel_main.setLayout(new java.awt.GridLayout(1, 3, 30, 0));

        jPanel_list_picture.setLayout(new javax.swing.BoxLayout(jPanel_list_picture, javax.swing.BoxLayout.Y_AXIS));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("List pictures");
        jPanel_list_picture.add(jLabel7);
        jPanel_list_picture.add(filler8);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {},
                        {},
                        {},
                        {}
                },
                new String [] {

                }
        ));
        jScrollPane4.setViewportView(jTable3);
        jTable3.getAccessibleContext().setAccessibleName("table_picture");

        jScrollPane_list_picture.setViewportView(jScrollPane4);

        jPanel_list_picture.add(jScrollPane_list_picture);

        jPanel_main.add(jPanel_list_picture);

        jPanel_input.setLayout(new javax.swing.BoxLayout(jPanel_input, javax.swing.BoxLayout.Y_AXIS));

        jPanel_customer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_customer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel_customer.setLayout(new javax.swing.BoxLayout(jPanel_customer, javax.swing.BoxLayout.Y_AXIS));

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label2.setText("Customer Infomation");
        jPanel_customer.add(label2);

        jPanel_cutomer_inner.setLayout(new javax.swing.BoxLayout(jPanel_cutomer_inner, javax.swing.BoxLayout.X_AXIS));
        jPanel_cutomer_inner.add(filler6);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel3.setToolTipText("input phone number and press enter to find customer");
        jPanel3.setLayout(new java.awt.GridLayout(3, 2, 0, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setLabelFor(textField_cus_name);
        jLabel2.setText("Name");
        jLabel2.setToolTipText("");
        jPanel3.add(jLabel2);

        textField_cus_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textField_cus_name.setName("customer_name"); // NOI18N
        jPanel3.add(textField_cus_name);
        textField_cus_name.getAccessibleContext().setAccessibleName("");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setLabelFor(textField_cus_addr);
        jLabel3.setText("Address");
        jLabel3.setToolTipText("");
        jPanel3.add(jLabel3);

        textField_cus_addr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textField_cus_addr.setName("customer_addr"); // NOI18N
        jPanel3.add(textField_cus_addr);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setLabelFor(textField_cus_phone);
        jLabel4.setText("Phone");
        jPanel3.add(jLabel4);

        textField_cus_phone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textField_cus_phone.setName("customer_phone"); // NOI18N
        jPanel3.add(textField_cus_phone);

        jPanel_cutomer_inner.add(jPanel3);
        jPanel_cutomer_inner.add(filler7);

        jPanel_customer.add(jPanel_cutomer_inner);
        jPanel_customer.add(filler3);

        jPanel_input.add(jPanel_customer);
        jPanel_input.add(filler4);

        jPanel_picture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_picture.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel_picture.setLayout(new javax.swing.BoxLayout(jPanel_picture, javax.swing.BoxLayout.Y_AXIS));

        label6.setAlignment(java.awt.Label.CENTER);
        label6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label6.setText("Picture");
        jPanel_picture.add(label6);

        jPanel_picture_inner.setLayout(new javax.swing.BoxLayout(jPanel_picture_inner, javax.swing.BoxLayout.X_AXIS));
        jPanel_picture_inner.add(filler1);

        jPanel5.setLayout(new java.awt.GridLayout(4, 2, 0, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setLabelFor(textField_pic_barcode);
        jLabel1.setText("Barcode");
        jPanel5.add(jLabel1);

        textField_pic_barcode.setName("picture_barcode"); // NOI18N
        jPanel5.add(textField_pic_barcode);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setLabelFor(textField_pic_name);
        jLabel5.setText("Name");
        jPanel5.add(jLabel5);

        textField_pic_name.setName("picture_name"); // NOI18N
        jPanel5.add(textField_pic_name);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setLabelFor(textField_pic_price);
        jLabel6.setText("Price");
        jPanel5.add(jLabel6);

        textField_pic_price.setName("picutre_price"); // NOI18N
        jPanel5.add(textField_pic_price);

        jButton_find_picture.setText("Find");
        jPanel5.add(jButton_find_picture);

        jButton_add_to_bill.setText("Add to bill");
        jPanel5.add(jButton_add_to_bill);

        jPanel_picture_inner.add(jPanel5);
        jPanel_picture_inner.add(filler2);

        jPanel_picture.add(jPanel_picture_inner);
        jPanel_picture.add(filler5);

        jPanel_input.add(jPanel_picture);

        jPanel_main.add(jPanel_input);

        jPanel_bill.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel_bill.setLayout(new javax.swing.BoxLayout(jPanel_bill, javax.swing.BoxLayout.X_AXIS));
        jPanel_bill.add(filler11);

        jPanel_bill_inner.setLayout(new javax.swing.BoxLayout(jPanel_bill_inner, javax.swing.BoxLayout.Y_AXIS));
        jPanel_bill_inner.add(filler9);

        jPanel_bill_info.setLayout(new java.awt.GridLayout(5, 2, 0, 10));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Bill No");
        jPanel_bill_info.add(jLabel8);

        jTextField_bill_no.setEditable(false);
        jTextField_bill_no.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel_bill_info.add(jTextField_bill_no);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Customer Name");
        jPanel_bill_info.add(jLabel9);

        jTextField_bill_customer_name.setEditable(false);
        jTextField_bill_customer_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel_bill_info.add(jTextField_bill_customer_name);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Address");
        jPanel_bill_info.add(jLabel10);

        jTextField_bill_customer_addr.setEditable(false);
        jTextField_bill_customer_addr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel_bill_info.add(jTextField_bill_customer_addr);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Phone");
        jPanel_bill_info.add(jLabel11);

        jTextField_bill_customer_phone.setEditable(false);
        jTextField_bill_customer_phone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel_bill_info.add(jTextField_bill_customer_phone);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Date");
        jPanel_bill_info.add(jLabel12);

        jTextField_bill_customer_date.setEditable(false);
        jTextField_bill_customer_date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel_bill_info.add(jTextField_bill_customer_date);

        jPanel_bill_inner.add(jPanel_bill_info);
        jPanel_bill_inner.add(filler13);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {},
                        {},
                        {},
                        {}
                },
                new String [] {

                }
        ));
        jScrollPane5.setViewportView(jTable4);
        jTable4.getAccessibleContext().setAccessibleName("table_bill");

        jScrollPane_bill.setViewportView(jScrollPane5);

        jPanel_bill_inner.add(jScrollPane_bill);

        jButton_bill_pay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_bill_pay.setText("Pay");

        jButton_bill_print.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_bill_print.setText("Print");

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));
        jPanel4.add(filler10);

        jPanel6.setLayout(new java.awt.GridLayout(2, 2, 0, 10));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Total");
        jPanel6.add(jLabel13);

        jTextField_bill_total.setEditable(false);
        jTextField_bill_total.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel6.add(jTextField_bill_total);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Staff");
        jPanel6.add(jLabel14);

        jTextField_bill_staff.setEditable(false);
        jTextField_bill_staff.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel6.add(jTextField_bill_staff);

        jPanel4.add(jPanel6);

        javax.swing.GroupLayout jPanel_bill_end_panelLayout = new javax.swing.GroupLayout(jPanel_bill_end_panel);
        jPanel_bill_end_panel.setLayout(jPanel_bill_end_panelLayout);
        jPanel_bill_end_panelLayout.setHorizontalGroup(
                jPanel_bill_end_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_bill_end_panelLayout.createSequentialGroup()
                                .addComponent(jButton_bill_pay)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_bill_print)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_bill_end_panelLayout.setVerticalGroup(
                jPanel_bill_end_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_bill_end_panelLayout.createSequentialGroup()
                                .addContainerGap(34, Short.MAX_VALUE)
                                .addGroup(jPanel_bill_end_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel_bill_end_panelLayout.createSequentialGroup()
                                                .addGroup(jPanel_bill_end_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jButton_bill_print, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                                        .addComponent(jButton_bill_pay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(1, 1, 1))
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10))
        );

        jPanel_bill_inner.add(jPanel_bill_end_panel);

        jPanel_bill.add(jPanel_bill_inner);
        jPanel_bill.add(filler12);

        jPanel_main.add(jPanel_bill);

        jPanel_navigator.setLayout(new java.awt.GridLayout(1, 4, 50, 0));

        jButton_manage_picture.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_manage_picture.setText("Manage Pictures");
        jPanel_navigator.add(jButton_manage_picture);

        jButton_manage_promotion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_manage_promotion.setText("Manage Promotion");
        jPanel_navigator.add(jButton_manage_promotion);

        jButton_manage_staff.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_manage_staff.setText("Manage Staff");
        jPanel_navigator.add(jButton_manage_staff);

        jButton_manage_customer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_manage_customer.setText("Manage Customer");
        jPanel_navigator.add(jButton_manage_customer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel_navigator, javax.swing.GroupLayout.DEFAULT_SIZE, 1132, Short.MAX_VALUE)
                                        .addComponent(jPanel_main, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addContainerGap())
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1132, Short.MAX_VALUE)
                                        .addContainerGap()))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jPanel_main, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel_navigator, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(854, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(start_menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(start_menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(start_menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(start_menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new start_menu_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JButton jButton_add_to_bill;
    private javax.swing.JButton jButton_bill_pay;
    private javax.swing.JButton jButton_bill_print;
    private javax.swing.JButton jButton_find_picture;
    private javax.swing.JButton jButton_manage_customer;
    private javax.swing.JButton jButton_manage_picture;
    private javax.swing.JButton jButton_manage_promotion;
    private javax.swing.JButton jButton_manage_staff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel_bill;
    private javax.swing.JPanel jPanel_bill_end_panel;
    private javax.swing.JPanel jPanel_bill_info;
    private javax.swing.JPanel jPanel_bill_inner;
    private javax.swing.JPanel jPanel_customer;
    private javax.swing.JPanel jPanel_cutomer_inner;
    private javax.swing.JPanel jPanel_input;
    private javax.swing.JPanel jPanel_list_picture;
    private javax.swing.JPanel jPanel_main;
    private javax.swing.JPanel jPanel_navigator;
    private javax.swing.JPanel jPanel_picture;
    private javax.swing.JPanel jPanel_picture_inner;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane_bill;
    private javax.swing.JScrollPane jScrollPane_list_picture;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField_bill_customer_addr;
    private javax.swing.JTextField jTextField_bill_customer_date;
    private javax.swing.JTextField jTextField_bill_customer_name;
    private javax.swing.JTextField jTextField_bill_customer_phone;
    private javax.swing.JTextField jTextField_bill_no;
    private javax.swing.JTextField jTextField_bill_staff;
    private javax.swing.JTextField jTextField_bill_total;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label6;
    private java.awt.TextField textField_cus_addr;
    private java.awt.TextField textField_cus_name;
    private java.awt.TextField textField_cus_phone;
    private java.awt.TextField textField_pic_barcode;
    private java.awt.TextField textField_pic_name;
    private java.awt.TextField textField_pic_price;
    // End of variables declaration
}
